dataset: 'replica'
project_name: 'Point_SLAM_replica'
use_view_direction: False
use_dynamic_radius: False
pointcloud:
  radius_add_max: 0.08
  radius_add_min: 0.02
meshing:
  eval_rec: True
tracking:
  filter: False
  kval: 5
  vis_freq: 200
  use_color_in_tracking: True
  w_color_loss: 0.5
  ignore_edge_W: 100
  ignore_edge_H: 100
  separate_LR: True
  const_speed_assumption: True
  lr: 0.002
  pixels: 1500
  iters: 40
  vis_inside_freq: 40
mapping:
  every_frame: 5
  BA: False
  color_refine: True
  vis_freq: 50
  vis_inside_freq: 1000
  ckpt_freq: 1000
  keyframe_every: 5 #20
  mapping_window_size: 12
  pixels: 5000
  pixels_adding: 6000
  pixels_based_on_color_grad: 1000
  iters_first: 1500
  iters: 300
  init:
    geometry:
      decoders_lr: 0.001
      geometry_lr: 0.03
      color_lr: 0.0
    color:
      decoders_lr: 0.005
      geometry_lr: 0.005
      color_lr:    0.005
  stage:
    geometry:
      decoders_lr: 0.001
      geometry_lr: 0.03
      color_lr: 0.0
    color:
      decoders_lr: 0.005
      geometry_lr: 0.005
      color_lr:    0.005
rendering:
  sample_near_pcl: False
  eval_img: True
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0